services:
  cloud-pin:
    build:
      dockerfile: Dockerfile.${DOCKER_MODE:-default}
      args:
        REMOTE_USER: ${USER}
        REMOTE_UID: ${REMOTE_UID:-1000}
        REMOTE_GID: ${REMOTE_GID:-1000}
    volumes:
      - ..:/workspace:cached
    networks:
      - dev

networks:
  dev:
    name: dev
    driver: bridge
